modules/Admin/routes/web.php
<?php

Route::group(['middleware' => ['web'], 'namespace' => 'Modules\Admin\Http\Controllers', 'prefix' => 'admin'], function () {

    Route::group(['middleware' => ['web']],
        function () {
            Route::middleware(['checkAdmin', 'counts'])->group(function () {
                Route::get('', 'AdminController@index')->name('adminsHome');
                Route::get('users/search', 'UsersController@search')->name('admin.users.search');
                Route::get('categories/search', 'CategoriesController@search')->name('admin.categories.search');
                Route::get('comments/search', 'CommentsController@search')->name('admin.comments.search');
                Route::get('communities/search', 'CommunitiesController@search')->name('admin.communities.search');
                Route::get('menus/search', 'MenusController@search')->name('admin.menus.search');
                Route::get('posts/search', 'PostsController@search')->name('admin.posts.search');
                Route::get('tags/search', 'TagsController@search')->name('admin.tags.search');

                Route::resource('menus', 'MenusController', ['as' => 'admin']);
                Route::resource('categories', 'CategoriesController', ['as' => 'admin']);
                Route::resource('users', 'UsersController', ['as' => 'admin']);
                Route::resource('tags', 'TagsController', ['as' => 'admin']);
                Route::resource('comments', 'CommentsController', ['as' => 'admin']);
                Route::resource('posts', 'PostsController', ['as' => 'admin']);

                Route::resource('communities', 'CommunitiesController', ['as' => 'admin']);
                Route::put('updateCommunityImage', 'CommunitiesController@changeImage');
                Route::put('updateCommentImage', 'CommentsController@changeImage');

                Route::post('tagsCheckbox/change', 'TagsController@tagsChange');
                Route::post('communitiesCheckbox/change', 'CommunitiesController@communitiesChange');
                Route::post('postsCheckbox/change', 'PostsController@postsChange');
                Route::post('categoryCheckbox/change', 'CommunitiesController@communityChange');
                Route::post('TagCheckbox/change', 'TagsController@tagsTagChange');
                Route::post('CategoryPostsCheckbox/change', 'CategoriesController@catsPostChange');

                Route::post('CommunityChangeTagsCheckbox/change', 'TagsController@communityChangeTagsCheck');
                Route::post('CommunityChangeUsersCheckbox/change', 'UsersController@communityChangeUsersCheck');
                Route::post('CommunityChangePostsCheckbox/change', 'PostsController@communityChangePostsCheck');
            });
        });
});

modules/Admin/Http/Controllers/CategoriesController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
//use Illuminate\Routing\Controller;
use Modules\Admin\Http\Requests\CategoryCreateRequest;
use Modules\Admin\Http\Requests\CategoryUpdateRequest;
use Modules\Main\Entities\Menu;
use Modules\Post\Entities\Category;
use Modules\Post\Entities\Post;

class CategoriesController extends Controller
{

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $categories = Category::orderBy('order')->paginate(4);

        return view('admin::modules.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create(Category $category)
    {
        return view('admin::modules.categories.item', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(CategoryCreateRequest $request)
    {
        if ($request->filled('slug')) {
            $slug = $request->input('slug');
        } else {
            $slug = str_slug($request->input('name'));
        }

        Category::create([
            'name'   => $request->name,
            'order'  => $request->order,
            'slug'   => $slug,
            'active' => $request->active
        ]);

        return redirect(route('admin.categories.index'));
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit(Category $category)
    {
        $menusCollection = Menu::all();
        $menus           = parent::dataSome($menusCollection, "menus", $category, 'belongsToMany');

        $postsCollection = Post::all();
        $posts           = parent::dataSome($postsCollection, "posts", $category, 'hasMany', 'category_id');

        $CategoryPostsUrl = '/admin/CategoryPostsCheckbox/change';

        return view('admin::modules.categories.item', compact('category', 'menus', 'posts'), [
            'CategoryPostsUrl' => $CategoryPostsUrl
        ]);
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(CategoryUpdateRequest $request, Category $category)
    {
        if ($request->filled('slug')) {
            $slug = $request->input('slug');
        } else {
            $slug = str_slug($request->input('name'));
        }

        $category->update([
            'name'   => $request->name,
            'order'  => $request->order,
            'slug'   => $slug,
            'active' => $request->active
        ]);

        $category->menus()->sync($request->checked);

        //$category->posts()


        return redirect(route('admin.categories.index'));
    }

    public function destroy(Request $request)
    {
        $id = intval($request->id);

        if ($id == 0) {
            return redirect()->back()->withErrors('Ой');
        }

        Post::where('category_id', $id)->update(['category_id' => 0]);

        $category = Category::find($id);
        $category->menus()->sync([]);
        $category->delete();

        return redirect()->back();
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search(Request $request)
    {
        $search_string = '%'.$request->get('search').'%';

        $categories = Category::where('name', 'like', $search_string)
            ->orderByDesc('id')
            ->paginate(10);

        return view('admin::modules.categories.index', compact('categories'));
    }

    public function catsPostChange(Request $request)
    {
        $category_id = $request->f_id;
        $post_id     = $request->l_id;

        $category = Category::find($category_id);
        $post     = Post::find($post_id);

        if ($request->parametr == 'true') {
            $post->category_id = $category_id;
        } elseif ($request->parametr == 'false') {
            $post->category_id = 0;
        }
        $post->save();

        return response()->json('ok');
    }
}

modules/Admin/resources/views/modules/categories/components/_categorie_item.blade.php
<div class="col-sm-12 profile">
    <div class="row card">
        <div class="card-header" style="display: flex; flex-direction: row;justify-content: space-between;">
            <h4 style="margin: 0;    padding-top: 2px;">Категории</h4>
            <a href="{{ route('admin.categories.create') }}" class="btn btn-primary" style="margin-top: 0;">
                <span class="fa fa-plus"></span>
                Добавить
            </a>
        </div>
        <div class="table-responsive">
            <table class="table" style="margin-bottom:0;">
                <tr>
                    <th>Название</th>
                    <th>Порядок</th>
                    <th>Активен</th>
                    <th>Путь</th>
                    <th>Действия</th>
                </tr>
                @foreach ($categories as $key)
                    <tr>
                        <td>
                            <strong class="badge">
                                <a href="{{ route('admin.categories.edit', ['slug' => $key->slug]) }}" target="_blank">
                                    {{ $key->name }}
                                </a>
                            </strong>
                        </td>
                        <td>{{ $key->order }}</td>
                        <td>{{ $key->active ? 'Да' : 'Нет' }}</td>
                        <td>{{ $key->slug }}</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a href="{{ route('admin.categories.edit', ['slug' => $key->slug]) }}"
                                   class="btn btn-sm btn-success">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                <form action="{{ route('admin.categories.destroy', $key->id) }}" method="post" style="margin-left:5px !important;">
                                    @csrf
                                    @method('delete')
                                    <input type="hidden" name="id" value="{{ $key->id }}">
                                    <button type="submit" class="btn btn-sm btn-danger"><i
                                                class="fa fa-trash"></i></button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>

modules/Admin/resources/views/modules/categories/components/_form.blade.php
<form action="{{ $category->id ? route('admin.categories.update', $category->slug) : route('admin.categories.store')}}"
      method="POST">
    @csrf
    @if($category->id)
        @method('put')
    @endif
    <div class="row">
        <div class="col-md-8 offset-2">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul style="list-style-type: none">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @if($category->id)
                <div class="row form-group">
                    <strong>Id</strong>
                    <input class="form-control" type="text" value="{{ $category->id }}" disabled>
                </div>
            @endif
            <div class="row form-group">
                <strong>Имя</strong>
                <input name="name" class="form-control" type="text" value="{{ $category->name }}">
            </div>
            <div class="row form-group">
                <strong>Порядок</strong>
                <input name="order" class="form-control" type="text" value="{{ $category->order }}">
            </div>
            <div class="row form-group">
                <strong>Путь</strong>
                <input name="slug" class="form-control" type="text" value="{{ $category->slug }}">
            </div>
            <div class="row form-check">
                <label>
                    <input name="active" class="form-check-input" type="checkbox" @if($category->active) checked @endif>
                    <strong>Активный</strong>
                </label>
            </div>
            @if($category->id)
                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample"
                        aria-expanded="false" aria-controls="collapseExample" style="width: 100% !important;">
                    Пункты Меню
                </button>
                <br>
                <hr>
                <div class="collapse" id="collapseExample">
                    <div class="card card-body">
                        <ul class="list-group w-200">
                            @foreach($menus as $key)
                                <li class="list-group-item">
                                    <div class="list-group-item list-group-item-action">
                                        <div class="form-check text-center">
                                            <div class="form-check">
                                                <input class="form-check-input"
                                                       type="checkbox"
                                                       value="{{ $key->id }}"
                                                       id="defaultCheck1"
                                                       {{ in_array($key->id, $category->menus->pluck('id')->toArray()) ? 'checked' : '' }}
                                                       name="checked[]">
                                                <label class="form-check-label" for="defaultCheck1">
                                                    {{ $key->title }}
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
                    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample3"
                            aria-expanded="false" aria-controls="collapseExample3" style="width: 100% !important;">
                        Посты
                    </button>
                    <br>
                    <hr>
                    <div class="collapse" id="collapseExample3">
                        <div class="card card-body">
                            @if(count($category->posts)==0)
                                <h4 class="text-center">Ничего не найдено</h4>
                            @endif
                            <div class="table-responsive">
                                <table class="tabulka_kariet table table-bordered table-hover">
                                    <thead>
                                    <tr class="alert alert-secondary" id="loadAjaxCategoryPosts" style="display:none">
                                        <td colspan="2" style="width:100%; text-align:center"><b><i
                                                        class="fa fa-spinner fa-spin" style="font-size:20px"></i></b>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Наименование</th>
                                        <th>Отношение</th>
                                    </tr>
                                    </thead>
                                    @foreach($posts as $key)
                                        <tr>
                                            <td>{{ $key->title }}</td>
                                            <td style='text-align:center'>
                                                <div class="form-check">
                                                    <input class="form-check-input"
                                                           type="checkbox"
                                                           id="defaultCheckkkkkk{{ $key->id }}"
                                                           @if(count($category->posts)>0)
                                                           @if($key->category_id == $category->id)
                                                           checked
                                                           @endif
                                                           @endif
                                                           onchange="CheckSwitch({{ $category->id }},{{ $key->id }},'loadAjaxCategoryPosts',{{ json_encode($CategoryPostsUrl) }},this)">
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                @endif
            <div class="row form-group">
                @if($category->id)
                    <input type="hidden" name="id" value="{{ $category->id }}">
                @else
                @endif
                <button class="btn btn-success btn-block" type="submit">Сохранить</button>
            </div>
        </div>
    </div>
</form>

modules/Admin/resources/views/modules/categories/components/_search.blade.php
<form method="GET" action="{{ route('admin.categories.search') }}" class="form-group row" style="margin-bottom: 0">
    <div class="col-md-12">
        <div class="input-group">
            <input type="text" class="form-control" name="search"
                   value="{{ Request::get('search') }}" placeholder="Введите строку для поиска">
            <span class="input-group-append">
                <button type="submit" class="btn btn-primary" style="margin-top: 0;">Найти</button>
            </span>
        </div>
    </div>
</form>