modules/Admin/routes/web.php
<?php

Route::group(['middleware' => ['web'], 'namespace' => 'Modules\Admin\Http\Controllers', 'prefix' => 'admin'], function () {

    Route::group(['middleware' => ['web']],
        function () {
            Route::middleware(['checkAdmin', 'counts'])->group(function () {
                Route::get('', 'AdminController@index')->name('adminsHome');
                Route::get('users/search', 'UsersController@search')->name('admin.users.search');
                Route::get('categories/search', 'CategoriesController@search')->name('admin.categories.search');
                Route::get('comments/search', 'CommentsController@search')->name('admin.comments.search');
                Route::get('communities/search', 'CommunitiesController@search')->name('admin.communities.search');
                Route::get('menus/search', 'MenusController@search')->name('admin.menus.search');
                Route::get('posts/search', 'PostsController@search')->name('admin.posts.search');
                Route::get('tags/search', 'TagsController@search')->name('admin.tags.search');

                Route::resource('menus', 'MenusController', ['as' => 'admin']);
                Route::resource('categories', 'CategoriesController', ['as' => 'admin']);
                Route::resource('users', 'UsersController', ['as' => 'admin']);
                Route::resource('tags', 'TagsController', ['as' => 'admin']);
                Route::resource('comments', 'CommentsController', ['as' => 'admin']);
                Route::resource('posts', 'PostsController', ['as' => 'admin']);

                Route::resource('communities', 'CommunitiesController', ['as' => 'admin']);
                Route::put('updateCommunityImage', 'CommunitiesController@changeImage');
                Route::put('updateCommentImage', 'CommentsController@changeImage');

                Route::post('tagsCheckbox/change', 'TagsController@tagsChange');
                Route::post('communitiesCheckbox/change', 'CommunitiesController@communitiesChange');
                Route::post('postsCheckbox/change', 'PostsController@postsChange');
                Route::post('categoryCheckbox/change', 'CommunitiesController@communityChange');
                Route::post('TagCheckbox/change', 'TagsController@tagsTagChange');
                Route::post('CategoryPostsCheckbox/change', 'CategoriesController@catsPostChange');

                Route::post('CommunityChangeTagsCheckbox/change', 'TagsController@communityChangeTagsCheck');
                Route::post('CommunityChangeUsersCheckbox/change', 'UsersController@communityChangeUsersCheck');
                Route::post('CommunityChangePostsCheckbox/change', 'PostsController@communityChangePostsCheck');
            });
        });
});

modules/Admin/Http/Controllers/TagsController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Modules\Admin\Http\Requests\CreateTagRequest;
use Modules\Admin\Http\Requests\UpdateTagRequest;
use Modules\Post\Entities\Tag;
use Modules\Users\Entities\Community;
use Modules\Users\Entities\User;

class TagsController extends Controller
{

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $tags = Tag::orderBy('order')->paginate(20);

        return view('admin::modules.tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     * @param Tag $tag
     * @return Response
     */
    public function create(Tag $tag)
    {
        return view('admin::modules.tags.item', compact('tag'));
    }

    /**
     * Store a newly created resource in storage.
     * @param  CreateTagRequest $request
     * @return Response
     */
    public function store(CreateTagRequest $request)
    {
        Tag::create($request->all());

        return redirect(route('admin.tags.index'));
    }

    /**
     * Show the form for editing the specified resource.
     * @param Tag $tag
     * @return Response
     */
    public function edit(Tag $tag)
    {
        $usersCollection = User::all();
        $users           = parent::dataSome($usersCollection, "users", $tag, 'belongsToMany');
        $tagsTagUrl      = '/admin/TagCheckbox/change';

        return view('admin::modules.tags.item', compact('tag', 'users'), [
            'tagsTagUrl' => $tagsTagUrl
        ]);
    }

    /**
     * Update the specified resource in storage.
     * @param  UpdateTagRequest $request
     * @param $tag Tag
     * @return Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        if ($request->filled('slug')) {
            $slug = $request->input('slug');
        } else {
            $slug = str_slug($request->input('name'));
        }

        $tag->update([
            'name'   => $request->input('name'),
            'slug'   => $slug,
            'order'  => $request->input('order'),
            'active' => $request->input('active')
        ]);

        return redirect()->route('admin.tags.index');
    }

    /**
     * Remove the specified resource from storage.
     * @param $tag Tag
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();

        return back();
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search(Request $request)
    {
        $search_string = '%'.$request->get('search').'%';

        $tags = Tag::where('name', 'like', $search_string)
            ->orderByDesc('id')
            ->paginate(10);

        return view('admin::modules.tags.index', compact('tags'));
    }

    public function tagsChange(Request $request)
    {
        $user_id = $request->f_id;
        $tag_id  = $request->l_id;

        $user = User::find($user_id);

        if ($request->parametr == 'true') {
            $user->tags()->attach($tag_id);
        } elseif ($request->parametr == 'false') {
            $user->tags()->detach($tag_id);
        }

        return response()->json('ok');
    }

    public function tagsTagChange(Request $request)
    {
        $tag_id  = $request->f_id;
        $user_id = $request->l_id;

        $tag = Tag::find($tag_id);

        if ($request->parametr == 'true') {
            $tag->users()->attach($user_id);
        } elseif ($request->parametr == 'false') {
            $tag->users()->detach($user_id);
        }

        return response()->json('ok');
    }

    public function communityChangeTagsCheck(Request $request)
    {
        $community_id = $request->f_id;
        $tag_id       = $request->l_id;

        $community = Community::find($community_id);

        if ($request->parametr == 'true') {
            $community->tags()->attach($tag_id);
        } elseif ($request->parametr == 'false') {
            $community->tags()->detach($tag_id);
        }

        return response()->json('ok');
    }

}

modules/Admin/resources/views/modules/tags/components/_form.blade.php
<form action="{{ $tag->id ? route('admin.tags.update', $tag->slug) : route('admin.tags.store')}}"
      method="POST">
    @csrf
    @if($tag->id)
        @method('put')
    @endif
    <div class="row">
        <div class="col-md-8 offset-2">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul style="list-style-type: none">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @if($tag->id)
                <div class="row form-group">
                    <strong>Id</strong>
                    <input class="form-control" type="text" value="{{ $tag->id }}" disabled>
                </div>
            @endif
            <div class="row form-group">
                <strong>Имя</strong>
                <input name="name" class="form-control" type="text" value="{{ $tag->name }}">
            </div>
            <div class="row form-group">
                <strong>Порядок</strong>
                <input name="order" class="form-control" type="text" value="{{ $tag->order }}">
            </div>
            <div class="row form-group">
                <strong>Путь</strong>
                <input name="slug" class="form-control" type="text" value="{{ $tag->slug }}">
            </div>
            <div class="row form-check">
                <label>
                    <input name="active" class="form-check-input" type="checkbox" @if($tag->active) checked @endif>
                    <strong>Активный</strong>
                </label>
            </div>
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample3"
                    aria-expanded="false" aria-controls="collapseExample3" style="width: 100% !important;">
                Пользователи
            </button>
            <br>
            <hr>
            <div class="collapse" id="collapseExample3">
                <div class="card card-body">
                    @if(count($tag->users)==0)
                        <h4 class="text-center">Ничего не найдено</h4>
                    @else
                    <div class="table-responsive">
                        <table class="tabulka_kariet table table-bordered table-hover">
                            <thead>
                            <tr class="alert alert-secondary" id="loadAjaxTagUsers" style="display:none">
                                <td colspan="2" style="width:100%; text-align:center"><b><i
                                                class="fa fa-spinner fa-spin" style="font-size:20px"></i></b>
                                </td>
                            </tr>
                            <tr>
                                <th>Наименование</th>
                                <th>Отношение</th>
                            </tr>
                            </thead>
                            @foreach($users as $key)
                                @if(count($tag->users)>0)
                                        <tr>
                                            <td>{{ $key->name }}</td>
                                            <td style='text-align:center'>
                                                <div class="form-check">
                                                    <input class="form-check-input"
                                                           type="checkbox"
                                                           id="defaultCheckkkkkk{{ $key->id }}"
                                                           @if(count($tag->users)>0)
                                                           @if(in_array($key->id, $tag->users->pluck('id')->toArray()))
                                                           checked
                                                           @endif
                                                           @endif
                                                           onchange="CheckSwitch({{ $tag->id }},{{ $key->id }},'loadAjaxTagUsers',{{ json_encode($tagsTagUrl) }},this)">
                                                </div>
                                            </td>
                                        </tr>
                                @endif
                            @endforeach
                        </table>
                    </div>
                    @endif
                </div>
            </div>
            <div class="row form-group">
                @if($tag->id)
                    <input type="hidden" name="id" value="{{ $tag->id }}">
                @else
                @endif
                <button class="btn btn-success btn-block" type="submit">Сохранить</button>
            </div>
        </div>
    </div>
</form>

modules/Admin/resources/views/modules/tags/components/_search.blade.php
<form method="GET" action="{{ route('admin.tags.search') }}" class="form-group row" style="margin-bottom: 0">
    <div class="col-md-12">
        <div class="input-group">
            <input type="text" class="form-control" name="search"
                   value="{{ Request::get('search') }}" placeholder="Введите строку для поиска">
            <span class="input-group-append">
                <button type="submit" class="btn btn-primary" style="margin-top: 0;">Найти</button>
            </span>
        </div>
    </div>
</form>

modules/Admin/resources/views/modules/tags/components/_tag_item.blade.php
<div class="col-sm-12 profile">
    <div class="row card">
        <div class="card-header" style="display: flex; flex-direction: row;justify-content: space-between;">
            <h4 style="margin: 0;    padding-top: 2px;">Теги</h4>
            <a href="{{ route('admin.tags.create') }}" class="btn btn-primary" style="margin-top: 0;">
                <span class="fa fa-plus"></span>
                Добавить
            </a>
        </div>
        <div class="table-responsive">
            <table class="table" style="margin-bottom:0;">
                <tr>
                    <th>Название</th>
                    <th>Путь</th>
                    <th>Порядок</th>
                    <th>Активен</th>
                    <th>Действия</th>
                </tr>
                @foreach ($tags as $tag)
                    <tr>
                        <td>
                            <strong class="badge">
                                <a href="{{ route('admin.tags.edit', $tag->id) }}" target="_blank">
                                    {{ $tag->name }}
                                </a>
                            </strong>
                        </td>
                        <td>{{ $tag->slug }}</td>
                        <td>{{ $tag->order }}</td>
                        <td>{{ $tag->active ? 'Да' : 'Нет' }}</td>
                        <td>
                            <a href="{{ route('admin.tags.edit', $tag->slug) }}" class="btn btn-sm btn-success">
                                <i class="fa fa-pencil"></i>
                            </a>
                            <a href="#" onclick="document.getElementById('del-form-{{$tag->id}}').submit()" class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i>
                            </a>
                            <form action="{{ route('admin.tags.destroy', $tag) }}" method="post" style="display: none;" id="del-form-{{$tag->id}}">
                                @csrf
                                @method('delete')
                            </form>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>