modules/Admin/routes/web.php
<?php

Route::group(['middleware' => ['web'], 'namespace' => 'Modules\Admin\Http\Controllers', 'prefix' => 'admin'], function () {

    Route::group(['middleware' => ['web']],
        function () {
            Route::middleware(['checkAdmin', 'counts'])->group(function () {
                Route::get('', 'AdminController@index')->name('adminsHome');
                Route::get('users/search', 'UsersController@search')->name('admin.users.search');
                Route::get('categories/search', 'CategoriesController@search')->name('admin.categories.search');
                Route::get('comments/search', 'CommentsController@search')->name('admin.comments.search');
                Route::get('communities/search', 'CommunitiesController@search')->name('admin.communities.search');
                Route::get('menus/search', 'MenusController@search')->name('admin.menus.search');
                Route::get('posts/search', 'PostsController@search')->name('admin.posts.search');
                Route::get('tags/search', 'TagsController@search')->name('admin.tags.search');

                Route::resource('menus', 'MenusController', ['as' => 'admin']);
                Route::resource('categories', 'CategoriesController', ['as' => 'admin']);
                Route::resource('users', 'UsersController', ['as' => 'admin']);
                Route::resource('tags', 'TagsController', ['as' => 'admin']);
                Route::resource('comments', 'CommentsController', ['as' => 'admin']);
                Route::resource('posts', 'PostsController', ['as' => 'admin']);

                Route::resource('communities', 'CommunitiesController', ['as' => 'admin']);
                Route::put('updateCommunityImage', 'CommunitiesController@changeImage');
                Route::put('updateCommentImage', 'CommentsController@changeImage');

                Route::post('tagsCheckbox/change', 'TagsController@tagsChange');
                Route::post('communitiesCheckbox/change', 'CommunitiesController@communitiesChange');
                Route::post('postsCheckbox/change', 'PostsController@postsChange');
                Route::post('categoryCheckbox/change', 'CommunitiesController@communityChange');
                Route::post('TagCheckbox/change', 'TagsController@tagsTagChange');
                Route::post('CategoryPostsCheckbox/change', 'CategoriesController@catsPostChange');

                Route::post('CommunityChangeTagsCheckbox/change', 'TagsController@communityChangeTagsCheck');
                Route::post('CommunityChangeUsersCheckbox/change', 'UsersController@communityChangeUsersCheck');
                Route::post('CommunityChangePostsCheckbox/change', 'PostsController@communityChangePostsCheck');
            });
        });
});

modules/Admin/Http/Controllers/PostsController.php
<?php

namespace Modules\Admin\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Modules\Admin\Http\Requests\UpdatePostRequest;
use Modules\Post\Entities\Category;
use Modules\Users\Entities\Community;
use Modules\Post\Entities\Tag;
use Modules\Post\Entities\Post;
use Modules\Users\Entities\User;

class PostsController extends Controller
{

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $posts = Post::orderBy('category_id')->paginate(4);

        return view('admin::modules.posts.index', compact('posts'));
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit(Post $post)
    {
        $categoriesCollection = Category::all();
        $categories = parent::dataSome($categoriesCollection, "posts", $post, 'hasMany', 'category_id');

        return view('admin::modules.posts.item', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        if ($request->has('unchecked')) {
            $checked = 0;
        } else {
            $checked = $request->input('checked',0);
        }

        $my      = $request->input('my', 0);
        $slug    = $request->input('slug', str_slug($request->input('name')));

        $post->update([
            'title'       => $request->title,
            'slug'        => $slug,
            'draft'       => $request->draft,
            'category_id' => $checked,
            'my'          => $my
        ]);

        return redirect(route('admin.posts.index'));
    }

    public function destroy(Request $request)
    {
        $id = intval($request->id);

        if ($id == 0) {
            return redirect()->back()->withErrors('Ой');
        }

        $post = Post::find($id);
        $post->delete();

        return redirect()->back();
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search(Request $request)
    {
        $search_string = '%'.$request->get('search').'%';

        $posts = Post::where('title', 'like', $search_string)
            ->orderByDesc('id')
            ->paginate(10);

        return view('admin::modules.posts.index', compact('posts'));
    }

    public function postsChange(Request $request)
    {
        $user_id = $request->f_id;
        $post_id = $request->l_id;

        $user = User::find($user_id);
        $post = Post::find($post_id);

        if ($request->parametr == 'true') {
            $post->user_id = $user_id;
        } elseif ($request->parametr == 'false') {
            $post->user_id = 0;
        }
        $post->save();

        return response()->json('ok');
    }

public function communityChangePostsCheck(Request $request)
{
    $community_id = $request->f_id;
    $post_id = $request->l_id;

    $community = Community::find($community_id);
    $post = Post::find($post_id);

    if ($request->parametr == 'true') {
        $post->community_id = $community_id;
    } elseif ($request->parametr == 'false') {
        $post->community_id = 0;
    }
    $post->save();

    return response()->json('ok');
  }
}

modules/Admin/resources/views/modules/posts/components/_form.blade.php
<form action="{{ route('admin.posts.update', $post->slug) }}"
      method="POST">
    @csrf
    @method('put')
    <div class="row">
        <div class="col-md-8 offset-2">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul style="list-style-type: none">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="row form-group">
                <strong>Id</strong>
                <input class="form-control" type="text" value="{{ $post->id }}" disabled>
            </div>
            <div class="row form-group">
                <strong>Имя</strong>
                <input name="title" class="form-control" type="text" value="{{ $post->title }}">
            </div>
            <div class="row form-group">
                <strong>Путь</strong>
                <input name="slug" class="form-control" type="text" value="{{ $post->slug }}">
            </div>
            <label>
                <input name="draft" class="form-check-input" type="checkbox"
                       @if($post->draft) checked @endif>
                <strong>Черновик</strong>
            </label>
            <br>
            <label>
                <input name="my" class="form-check-input" type="checkbox"
                       @if($post->my) checked @endif>
                <strong>Моё</strong>
            </label>
                <hr>
            <button class="btn btn-primary" type="button" data-toggle="collapse"
                    data-target="#collapseExample"
                    aria-expanded="false" aria-controls="collapseExample" style="width: 100% !important;">
                Категории
            </button>
            <br>
            <hr>
            <div class="collapse" id="collapseExample">
                <div class="card card-body">
                    <ul class="list-group w-200">
                        <li class="list-group-item">
                            <div class="list-group-item list-group-item-action">
                                <div class="form-check text-center">
                                    <div class="form-check">
                                        <div class="form-check">
                                            <input class="form-check-input"
                                                   type="checkbox"
                                                   name="unchecked"
                                                   id="exampleRadios2"
                                                   @if($post->category_id==0)
                                                   checked
                                                    @endif>
                                            <label class="form-check-radio" for="exampleRadios2">
                                                Ничего
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        @foreach($categories as $key)
                            <li class="list-group-item">
                                <div class="list-group-item list-group-item-action">
                                    <div class="form-check text-center">
                                        <div class="form-check">
                                            <div class="form-check">
                                                <input class="form-check-input"
                                                       type="radio"
                                                       name="checked"
                                                       id="exampleRadios2"
                                                       @if($key->id == $post->category_id)
                                                       checked
                                                       @endif
                                                       value="{{ $key->id }}">
                                                <label class="form-check-label" for="exampleRadios2">
                                                    {{ $key->name }}
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
            <div class="row form-group">
                <input type="hidden" name="id" value="{{ $post->id }}">
                <button class="btn btn-success btn-block" type="submit">Сохранить</button>
            </div>
        </div>
    </div>
</form>

modules/Admin/resources/views/modules/posts/components/_post_item.blade.php
<div class="col-sm-12 profile">
    <div class="row card">
        <div class="card-header" style="display: flex; flex-direction: row;justify-content: space-between;">
            <h4 style="margin: 0;    padding-top: 2px;">Посты</h4>
        </div>
        <div class="table-responsive">
            <table class="table" style="margin-bottom:0;">
                <tr>
                    <th>Название</th>
                    <th>Автор</th>
                    <th>Путь</th>
                    <th>Рейтинг</th>
                    <th>Черновик</th>
                    <th>Мой</th>
                    <th>Время публикации</th>
                    <th>Действия</th>
                </tr>
                @foreach ($posts as $key)
                    <tr>
                        <td>
                            <strong class="badge">
                                <a href="{{ route('admin.posts.edit', ['slug' => $key->slug]) }}" target="_blank">
                                    {{ str_limit($key->title,10,'...') }}
                                </a>
                            </strong>
                        </td>
                        <td>@if($key->user) {{ str_limit($key->user->name,50,'...') }} @else - @endif</td>
                        <td>{{ str_limit($key->slug,15,'...') }}</td>
                        <td>{{ $key->rating }}</td>
                        <td>{{ $key->draft ? 'Да' : 'Нет' }}</td>
                        <td>{{ $key->my ? 'Да' : 'Нет' }}</td>
                        <td>{{ $key->created_at }}</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a href="{{ route('admin.posts.edit', ['slug' => $key->slug]) }}"
                                   class="btn btn-sm btn-success">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                <form action="{{ route('admin.posts.destroy', $key->id) }}" method="post" style="margin-left:5px !important;">
                                    @csrf
                                    @method('delete')
                                    <input type="hidden" name="id" value="{{ $key->id }}">
                                    <button type="submit" class="btn btn-sm btn-danger"><i
                                                class="fa fa-trash"></i></button>
                                </form>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>
</div>

modules/Admin/resources/views/modules/posts/components/_search.blade.php
<form method="GET" action="{{ route('admin.posts.search') }}" class="form-group row" style="margin-bottom: 0">
    <div class="col-md-12">
        <div class="input-group">
            <input type="text" class="form-control" name="search"
                   value="{{ Request::get('search') }}" placeholder="Введите строку для поиска">
            <span class="input-group-append">
                <button type="submit" class="btn btn-primary" style="margin-top: 0;">Найти</button>
            </span>
        </div>
    </div>
</form>